### ISSUE TITLE
Connect learner survfit (nelson aalen) & parametric (survreg) from package survival

### ISSUE THREAD

**Issue by RaphaelS1** [mlr-org/mlr3learners#84]
https://github.com/mlr3learners/mlr3learners.survival

**Comment by RaphaelS1** [comment]
The instructions are a bit confusing about what to actually do once the learner is made from my side.

Option 1:

* Open an issue in mlr3learners following the issue template. (If you don't want to add the learner yourself, you are done here. We might take your vote into consideration but can't promise when your requested learner will be available.)

Option 2:

* Open a Pull Request in the mlr3learners repo to add your learner to the list of "In Progress" learners. Once approved, it will be moved to the "Approved" section.

Let me know if only 2. is needed and I'll close this

**Comment by pat-s** [comment]
Both are true.

1) Is before you start working on the learner. The issue is to have an overview about learners that users want / are being worked on in the mlr3learners repo. It might take a while between creating this issue and finalizing the learner.

2) Applies when the learner has been implemented as a first draft. The PR is for adding the learner to the vignette which lists all learners.

**Comment by RaphaelS1** [comment]
Okay, so going forward I won't open issues then as in theory all my learners are already implemented and working

**Comment by RaphaelS1** [comment]
Although one thing I wasn't sure about is the `packages` field. In [the book](https://mlr3book.mlr-org.com/extending-learners.html) it says that this should be all packages required to run the learner but the template implies that only a single package should go in that field, also the template breaks if multiple are supplied.

**Comment by pat-s** [comment]
Good find! I'd say this should always just default to the upstream package of the learner since we are operating on a per-package base. I'll change it in the book.

**Comment by RaphaelS1** [comment]
I always read it to mean: "the packages that must be installed in order for this learner to work". And not "the package from which this learner is implemented".

**Comment by pat-s** [comment]
# Review

Thanks. Did you have a look at the [submission checklist](https://github.com/mlr-org/mlr3learners.template/issues/5)?
I assume some of these points will also apply to coxboost - let me know when you have implemented all points :)

- [ ] fix lintr

- [ ] apply mlr-style

- [ ] empty functions? https://github.com/mlr3learners/mlr3learners.survival/blob/14ee1f52883d103f5dc263a7e5796019f2213888/R/predict_survreg.R#L60-L63

- [ ] Rather than using custom code you can tag these control paramters with "control" in the ParamSet and then query them explicitly in `.train()`: https://github.com/mlr3learners/mlr3learners.survival/blob/14ee1f52883d103f5dc263a7e5796019f2213888/R/LearnerSurvParametric.R#L86-L87

- [ ] suggest using `mlr3misc::stopf(wrap = TRUE)`: https://github.com/mlr3learners/mlr3learners.survival/blob/14ee1f52883d103f5dc263a7e5796019f2213888/R/LearnerSurvParametric.R#L135

- [ ] I am aiming that we become specific in prefixing functions from external packages, i.e. `mlr3misc::invoke(mlr3proba::predict_survreg)`

- [ ] Something seems to be missing here: https://github.com/mlr3learners/mlr3learners.survival/blob/14ee1f52883d103f5dc263a7e5796019f2213888/R/LearnerSurvParametric.R#L14

**Comment by RaphaelS1** [comment]
> Did you have a look at the submission checklist?

Every step, sorry if I missed something

>  fix lintr

From what I can see (https://github.com/mlr3learners/mlr3learners.survival/commit/14ee1f52883d103f5dc263a7e5796019f2213888) the only problems are the case of .onLoad and .onUnload, which we can't change.

>  apply mlr-style

I applied the style using `styler`, is there anything else I need to do for this?

> https://github.com/mlr3learners/mlr3learners.survival/blob/14ee1f52883d103f5dc263a7e5796019f2213888/R/predict_survreg.R#L60-L63

Not empty, just easier to define the body separately using substitute and keep the common formal

>  suggest using mlr3misc::stopf(wrap = TRUE):

Ah this is very useful! Thanks

> Rather than using custom code you can tag these control paramters with "control" in the ParamSet and then query them explicitly in .train()

This confuses me because from my understanding if you tag something as c("train", "control") then don't these parameters get included with `self$param_set$get_values(tags = "train")`

**Comment by pat-s** [comment]
> From what I can see (mlr3learners/mlr3learners.survival@14ee1f5) the only problems are the case of .onLoad and .onUnload, which we can't change.

You need to add `# nolint` add the end of these lines. I already did so in the template - I thought this is known, sorry.

> This confuses me because from my understanding if you tag something as c("train", "control") 

Yes they do - but you do a custom diff to extract the control params amd pass them via `pv$control` - this is easier when you query those via the control tags. I also makes it more visible which ones are from a control object by just looking at the ParamSet.

> So are we changing learners like these /R/LearnerClassifGlmnet.R@master ?

No. I explained in a new [mlr3book paragraph](https://mlr3book.mlr-org.com/extending-learners.html#learner-control) which I added two days ago.

> Edit: sorry just saw the mlr3book and how invoke now has the option for control parameters

😄 👍 

Keep asking, there are still some undocumented edge cases 👍 

Another point I just saw: You are calling the constructor of the super class [directly with the ParamSet](https://github.com/mlr3learners/mlr3learners.survival/blob/0ed7a1db9827d3202af1e3f4e5a82cfa4baefb74/R/LearnerSurvNelson.R#L30-L37). While this is not problematic per se, it makes it impossible to define Parameter dependencies within the ParamSet via `ps$add_dep()`. Even if your learner has no parameter dependencies, it would be great if we could stick to this skeleton for all learners. See [here](https://github.com/mlr-org/mlr3learners/blob/0a4e673df84458706886b705fd956ed0158a362a/R/LearnerClassifXgboost.R#L74-L79) for an example.

**Comment by RaphaelS1** [comment]
> You need to add # nolint add the end of these lines. I already did so in the template - I thought this is known, sorry.

Sorry this is probably because I'm not familiar with lintr but I can see `# nolint` in the `zzz.R` https://github.com/mlr3learners/mlr3learners.survival/blob/master/R/zzz.R#L22 , is there something else to add?

> Yes they do - but you do a custom diff to extract the control params amd pass them via pv$control - this is easier when you query those via the control tags. I also makes it more visible which ones are from a control object by just looking at the ParamSet.

> No. I explained in a new mlr3book paragraph which I added two days ago.

These two together, along with the book are confusing to me. Because your first answer seems to imply that we should always separately tag control and non-control parameters and then separate them as required, which is supported by the book, but the code for `glmnet` (https://github.com/mlr-org/mlr3learners/blob/master/R/LearnerClassifGlmnet.R) doesn't use these tags and just checks them against the control names. 

This is also further confusing because in the book example there is no custom diff and the arguments passed to `.args` overlap with those passed to `control`, which is okay if inside `invoke` it does setdiff on named and unnamed arguments, but it isn't stated in the docs if this is the case. The example is further complicated as some learners (admittedly this is poor implementation) expect control to be an object and not a named list of parameters!

I don't think this is a fault of documentation on your side but just that every learner is very different in how they use controls and I'm just finding it hard to make sure I'm doing the correct option for the given case. My confusion may be clearer in https://github.com/mlr3learners/mlr3learners.coxboost/blob/master/R/LearnerSurvCVCoxboost.R, in which there are two separate stages before `train` and so could require two extra parameter tags! 

> Another point I just saw: You are calling the constructor of the super class directly with the ParamSet. While this is not problematic per se, it makes it impossible to define Parameter dependencies within the ParamSet via ps$add_dep(). Even if your learner has no parameter dependencies, it would be great if we could stick to this skeleton for all learners. See here for an example.

Sure, I mix this in learners, but you're right it's much better to be consistent

**Comment by pat-s** [comment]
> Sorry this is probably because I'm not familiar with lintr but I can see # nolint in the zzz.R mlr3learners/mlr3learners.survival:R/zzz.R@master#L22 , is there something else to add?

It needs to be exactly on the problematic line.
It looks like you've run `styler::` which might have shifted the comment to a new line. There was a regression some days ago which is already fixed. You just need to update your installation of {styler}.

> These two together, along with the book are confusing to me. Because your first answer seems to imply that we should always separately tag control and non-control parameters and then separate them as required, which is supported by the book, but the code for glmnet (/R/LearnerClassifGlmnet.R@master ) doesn't use these tags and just checks them against the control names.

Learners in {mlr3learners} are not consistent; I am still in the process of cleaning up.

> always separately tag control and non-control parameters and then separate them as required

Yes, please do this. Hopefully at some point I've catched up aligning all learners to this approach.
I did not do the first implementation of {mlr3learners} and right now trying to clean up and align everything with more strict and clear rules.

> The example is further complicated as some learners (admittedly this is poor implementation) expect control to be an object and not a named list of parameters!

Yeah nothing we can do against this. In this case you can still get the params and pass them in the correct format to the learner (list, no list, etc.).

> in which there are two separate stages before train and so could require two extra parameter tags!

Just do so, tags are just to help querying a certain set of params. They can have an infinite number of tags and you can just look at them as "groups".

**Comment by RaphaelS1** [comment]
Understood! I'll make sure I get tagging from now on. I've added `# nolint` properly now, so your checklist above should be all done for `mlr3learners.survival`. I'll add control tags to `mlr3learners.coxboost` and put a message in that issue when that's done with the `lintr` stuff as well.

The build seems to be erroring on mac devel for everything so I assume this is unrelated to this package, but everything else is passing :)

**Comment by pat-s** [comment]
Thanks! I just got reminded that we should also include the S3 predict funs into the ParamTest.
After this, do you want to go ahead and add the learner to mlr3learners.drat by following the instructions in its README?

The first learner always takes a bit longer but once you did everything once, all others will be much easier :)

- [ ] Add ParamTest for predict functions

- [ ] Add to mlr3learners.drat

- [ ] Make a GitHub release

- [ ] Celebrate 🎉  😅

**Comment by RaphaelS1** [comment]
Actually in this package neither function has a `predict' dispatch so that was easy!

**Comment by RaphaelS1** [comment]
Can you add me to the `mlr3learners.drat` team please?

**Comment by RaphaelS1** [comment]
Gist is erroring after running
```R
gh::gh("GET /repos/:owner/:repo/actions/secrets/public-key",
                   owner = travis::get_owner("origin"),
                   repo = travis::get_repo("origin")
  )
```

I get:

```
Error in gh_process_response(raw) : 
GitHub API error (403): 403 Forbidden
Message: Must have admin rights to Repository.
Read more at https://developer.github.com/v3/actions/secrets/#get-your-public-key
```

**Comment by pat-s** [comment]
You're in now. I've sent you an invitation beforehand which did not arrive/you did not see? Anyway, it should work now? :)

**Comment by RaphaelS1** [comment]
Didn't see it before, I'm still getting the same error though not sure what I'm doing wrong!
